[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
omnifarming = "B61XPDSuobij3c4aBvyeVmKfBJVdTzkV2Xn4TpM1AtGS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/meadowilla/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
